# Generated by Django 5.2.1 on 2025-05-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppa',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ppa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ppa_images'),
        ),
    ]
