# Generated by Django 5.2.1 on 2025-06-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0003_ppa_address_ppa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppa',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
