# Generated by Django 5.2.1 on 2025-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0004_ppa_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppa',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='image',
            field=models.ImageField(default=1, upload_to='ppa_images/'),
            preserve_default=False,
        ),
    ]
