# Generated by Django 5.2.1 on 2025-06-14 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0006_ppa_updated_at_alter_ppa_posted_by_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])]),
        ),
    ]
