# Generated by Django 5.2.1 on 2025-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0007_userprofile_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppa',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='lga',
            field=models.CharField(max_length=100),
        ),
    ]
