# Generated by Django 5.2.1 on 2025-06-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppa',
            name='verification_document',
            field=models.ImageField(blank=True, help_text='Upload PPA posting letter or clearance letter or clear photo of PPA for verification', null=True, upload_to='ppa_verifications/'),
        ),
        migrations.AddField(
            model_name='ppa',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of verification request', max_length=20),
        ),
        migrations.AddField(
            model_name='ppa',
            name='verified',
            field=models.BooleanField(default=False, help_text='Set to True after admin verification'),
        ),
    ]
