# Generated by Django 5.2.1 on 2025-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0010_ppa_verification_document_ppa_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppa',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text='Status of verification request', max_length=20),
        ),
    ]
