# Generated by Django 5.2.1 on 2025-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0011_alter_ppa_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppa',
            name='accommodation_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
