# Generated by Django 5.2.1 on 2025-06-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0012_alter_ppa_accommodation_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow user to appear on the leaderboard'),
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('total_ppas', models.IntegerField(default=0)),
                ('verified_ppas', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-total_ppas'],
            },
        ),
    ]
