# Generated by Django 5.2.1 on 2025-06-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0013_leaderboardreset_userprofile_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_follow',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone follows you.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_leaderboard',
            field=models.BooleanField(default=True, help_text='Receive notifications when you appear on the leaderboard.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_post',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone I follow posts.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_rating',
            field=models.BooleanField(default=True, help_text='Receive notifications when a post is rated.'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('follow', 'Follow'), ('rating', 'Rating'), ('leaderboard', 'Leaderboard'), ('post', 'Post from Followed')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
