# Generated by Django 5.2.3 on 2025-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0016_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ppareview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
