# Generated by Django 5.2.3 on 2025-07-19 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0018_marketplacefeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='nysc.ppa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ppa'], name='nysc_userbo_user_id_00cf69_idx')],
                'unique_together': {('user', 'ppa')},
            },
        ),
    ]
