# Generated by Django 5.2.3 on 2025-07-27 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0019_userbookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='nysc_notifi_user_id_0f8f67_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='nysc_notifi_user_id_b5bbc2_idx'),
        ),
    ]
